/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: Aki_Kato (https://sketchfab.com/Aki_Kato)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ungranned-gem-c737cef5da8b4ce18614a40d78123127
Title: Ungranned Gem
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props: any) {
  const { nodes, materials } = useGLTF('/gem.gltf')
  const mesh = useRef<any>(null)
  useFrame(({ clock }) => {
    mesh.current.rotation.y = clock.getElapsedTime()
    mesh.current.rotation.x = Math.sin(clock.getElapsedTime()) / 2
  })
  return (
    <group ref={mesh} {...props} dispose={null}>
      <mesh geometry={(nodes as any).Group4992001__0.geometry} material={materials['Scene_-_Root']} scale={100} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
